package views;



import javax.swing.JOptionPane;
import model.Fornecedor;
import model.FornecedorDAO;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pc
 */
public class CadastroFornecedor extends javax.swing.JFrame {

    /**
     * Creates new form Fornecedor
     */
    
    
    
    RemoverFornecedor rmf =new RemoverFornecedor();
    
    public CadastroFornecedor() {
        initComponents();
        CampoNome.setEnabled(false);
        CampoCodigo.setEnabled(false);
        BNovo.setEnabled(true);
        BRemover.setEnabled(false);
        BAlterar.setEnabled(false);
        BSalvar.setEnabled(false);
        BAnt.setEnabled(false);
        BProx.setEnabled(false);
        
    }

    Principal p;
    int forne;

    public Principal getP() {
        return p;
    }

    public void setP(Principal p) {
        this.p = p;
    }
    
    public int Buscacod(int cod){
        
        for(int i=0;i<=p.contf;i++){
            
            if(p.fornecedor[i].getCodigoF()==cod){
                return 1; 
            }
        }
        
                
        return 0;
    }
    
    
    public void Exibir(int cad){
        
        try{
            
            CampoNome.setText(p.fornecedor[cad].getNomeF());
            CampoCodigo.setText(Integer.toString(p.fornecedor[cad].getCodigoF()));
           
           
        }catch(ArrayIndexOutOfBoundsException e){
            
            JOptionPane.showMessageDialog(null,"Sem informacoes para tras!");
        
            
        }catch(NullPointerException e){
            
            
            JOptionPane.showMessageDialog(null, "Sem informacoes para frente!");   
                
                
        }
        
        
        
    }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CampoNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CampoCodigo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        BSalvar = new javax.swing.JButton();
        BNovo = new javax.swing.JButton();
        BAlterar = new javax.swing.JButton();
        BRemover = new javax.swing.JButton();
        BAnt = new javax.swing.JButton();
        BProx = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fornecedor");

        jLabel2.setText("Nome");

        jLabel3.setText("Código");

        CampoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCodigoActionPerformed(evt);
            }
        });

        BSalvar.setText("Salvar");
        BSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSalvarActionPerformed(evt);
            }
        });

        BNovo.setText("Novo");
        BNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNovoActionPerformed(evt);
            }
        });

        BAlterar.setText("Alterar");
        BAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAlterarActionPerformed(evt);
            }
        });

        BRemover.setText("Remover");
        BRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRemoverActionPerformed(evt);
            }
        });

        BAnt.setText("Anterior");
        BAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAntActionPerformed(evt);
            }
        });

        BProx.setText("Próximo");
        BProx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BProxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CampoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BRemover)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(BAnt)
                        .addGap(18, 18, 18)
                        .addComponent(BProx)
                        .addGap(132, 132, 132))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(BSalvar)
                        .addGap(23, 23, 23))))
            .addComponent(jSeparator3)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jSeparator4)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BSalvar)
                    .addComponent(BNovo)
                    .addComponent(BAlterar)
                    .addComponent(BRemover))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BAnt)
                    .addComponent(BProx))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNovoActionPerformed

               CampoNome.setEnabled(true);
               CampoCodigo.setEnabled(true);
               CampoNome.setText("");
               CampoCodigo.setText("");
               BNovo.setEnabled(false);
               BSalvar.setEnabled(true);
               BRemover.setEnabled(true);
               BAlterar.setEnabled(true);
               BProx.setEnabled(true);
               BAnt.setEnabled(true);
        
        
        
        
    }//GEN-LAST:event_BNovoActionPerformed

    private void BSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSalvarActionPerformed
        if(p.contf==9){
            
            JOptionPane.showMessageDialog(null,"Limite máximo de fornecedores cadastrados!"+"\n");
            
        }else{
            
            if(Buscacod(Integer.parseInt(CampoCodigo.getText()))==1){
                
              JOptionPane.showMessageDialog(null,"O código já está sendo utilizado,informe novamente!");
              
            }else{
                
                p.contf++;
                forne=p.contf;
                p.fornecedor[p.contf]=new Fornecedor();
                p.fornecedor[p.contf].CadastrarF(Integer.parseInt(CampoCodigo.getText()),CampoNome.getText());
                FornecedorDAO.salvar(p.fornecedor[p.contf]); 
                
                
                CampoNome.setEnabled(false);
                CampoCodigo.setEnabled(false);
                
                BSalvar.setEnabled(false);
                BNovo.setEnabled(true);
                BAlterar.setEnabled(true);
                BRemover.setEnabled(true);
                BProx.setEnabled(true);
                BAnt.setEnabled(true);
                
                
               
                
                
                
                
                
            }
            
        }
    }//GEN-LAST:event_BSalvarActionPerformed

    private void CampoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCodigoActionPerformed

    private void BAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAlterarActionPerformed
        
        if(p.contf==-1){
            JOptionPane.showMessageDialog(null,"Não há fornecedores cadastrados!");
        
        }else{
            
        
        if(BAlterar.getText().equals("Alterar")){
            
            CampoNome.setEnabled(true);
            CampoCodigo.setEnabled(true);
       
            BSalvar.setEnabled(false);
            BRemover.setEnabled(false);
            BProx.setEnabled(false);
            BAnt.setEnabled(false);
            BNovo.setEnabled(false);
            
            BAlterar.setText("Salvar");
    
            
        }else{
            int opcao;
            opcao=JOptionPane.showConfirmDialog(null,"Realmente deseja alterar os dados?","Alterando...",JOptionPane.OK_CANCEL_OPTION);
         
             if(opcao==0){
            
            p.fornecedor[forne].CadastrarF(Integer.parseInt(CampoCodigo.getText()),CampoNome.getText());
            CampoNome.setEnabled(false);
            CampoCodigo.setEnabled(false);
            
            BSalvar.setEnabled(false);
            BProx.setEnabled(true);
            BAnt.setEnabled(true);
            BRemover.setEnabled(true);
            BNovo.setEnabled(true);
            
            BAlterar.setText("Alterar");
            
            
              }
           }  
        }
          
    }//GEN-LAST:event_BAlterarActionPerformed

    private void BRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRemoverActionPerformed
        
        if(p.contf==-1){
            JOptionPane.showMessageDialog(null,"Não há fornecedores cadastrados!");
            
        }else{
            
            rmf.setVisible(true);
            rmf.setP(p);
            
            
            
            
        }
    }//GEN-LAST:event_BRemoverActionPerformed

    private void BProxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BProxActionPerformed
        if(forne == p.contf){
            Exibir(forne+1);
            
        }else{
        
            forne++;
            Exibir(forne);
        }
    }//GEN-LAST:event_BProxActionPerformed

    private void BAntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAntActionPerformed
         if(forne ==0){
            Exibir(forne-1);
            
            
        }else{
            
            forne--;
            Exibir(forne);
        }
    }//GEN-LAST:event_BAntActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAlterar;
    private javax.swing.JButton BAnt;
    private javax.swing.JButton BNovo;
    private javax.swing.JButton BProx;
    private javax.swing.JButton BRemover;
    private javax.swing.JButton BSalvar;
    private javax.swing.JTextField CampoCodigo;
    private javax.swing.JTextField CampoNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
