package views;


import javax.swing.JOptionPane;
import model.Movimento;
import model.Cliente;
import model.MovimentoDAO;
import model.Produto;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pc
 */
public class CadastroMovimento extends javax.swing.JFrame {

    /**
     * Creates new form CadastroMovimento
     */
    
    Principal p;

    public Principal getP() {
        return p;
    }

    public void setP(Principal p) {
        this.p = p;
    }
    
    
    
    
    public CadastroMovimento() {
        initComponents();
        setLocationRelativeTo( null );
        BNovo.setEnabled(true);
        BAlterar.setEnabled(false);
        BRemover.setEnabled(false);
        BSalvar.setEnabled(false);
        BAnt.setEnabled(false);
        BProx.setEnabled(false);
        
        NomeCliente.setEnabled(false);
        CodigoCliente.setEnabled(false);
        DataVenda.setEnabled(false);
        NomeCliente.setEnabled(false);
        CodVenda.setEnabled(false);
        Pagamento.setEnabled(false);
        
        p1.setEnabled(false);
        p2.setEnabled(false);
        p3.setEnabled(false);
        p4.setEnabled(false);
        p5.setEnabled(false);
        
        
        q1.setEnabled(false);
        q2.setEnabled(false);
        q3.setEnabled(false);
        q4.setEnabled(false);
        q5.setEnabled(false);
        
        v1.setEnabled(false);
        v2.setEnabled(false);
        v3.setEnabled(false);
        v4.setEnabled(false);
        v5.setEnabled(false);
        
        vv1.setEnabled(false);
        vv2.setEnabled(false);
        vv3.setEnabled(false);
        vv4.setEnabled(false);
        vv5.setEnabled(false);
        
        
        TOTAL.setEnabled(false);
        
        
        
        
        
    }
    
    int posicaoc = 0;
    int posicaop = 0;
    
    public int Buscacod(int codigo){
        
        for(int i=0;i<=p.cont;i++){
           if(p.cliente[i].getCodigo()==codigo){
               posicaoc = i;
               return 1; 
           }
        }
        return 0;
        
        
    }
    
    public int Buscaprod(int codp){
        
        for(int i=0;i<=p.contp;i++){
           if(p.produto[i].getCodigoP()==codp){ 
           posicaop = i;
           return i;
           }
        }
        return -1;
        
        
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CodigoCliente = new javax.swing.JTextField();
        CodVenda = new javax.swing.JTextField();
        DataVenda = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        p1 = new javax.swing.JTextField();
        p2 = new javax.swing.JTextField();
        p3 = new javax.swing.JTextField();
        p4 = new javax.swing.JTextField();
        p5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        q1 = new javax.swing.JTextField();
        q2 = new javax.swing.JTextField();
        q3 = new javax.swing.JTextField();
        q4 = new javax.swing.JTextField();
        q5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        BRemover = new javax.swing.JButton();
        BAlterar = new javax.swing.JButton();
        BAnt = new javax.swing.JButton();
        BNovo = new javax.swing.JButton();
        BSalvar = new javax.swing.JButton();
        BProx = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        v1 = new javax.swing.JLabel();
        v2 = new javax.swing.JLabel();
        v3 = new javax.swing.JLabel();
        v4 = new javax.swing.JLabel();
        v5 = new javax.swing.JLabel();
        vv1 = new javax.swing.JLabel();
        vv2 = new javax.swing.JLabel();
        vv3 = new javax.swing.JLabel();
        vv4 = new javax.swing.JLabel();
        vv5 = new javax.swing.JLabel();
        TOTAL = new javax.swing.JLabel();
        Pagamento = new javax.swing.JTextField();
        NomeCliente = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Movimento");

        jLabel1.setText("Código Venda");

        jLabel2.setText("Forma de pagamento");

        jLabel3.setText("Data da venda");

        jLabel4.setText("Nome do Cliente");

        jLabel5.setText("Código");

        jLabel6.setText("Código do produto");

        p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1ActionPerformed(evt);
            }
        });

        p5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p5ActionPerformed(evt);
            }
        });

        jLabel7.setText("Quantidade");

        q1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Valor unitário");

        jLabel9.setText("Valor da venda");

        BRemover.setText("Remover");

        BAlterar.setText("Alterar");

        BAnt.setText("Anterior");

        BNovo.setText("Novo");
        BNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNovoActionPerformed(evt);
            }
        });

        BSalvar.setText("Salvar");
        BSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSalvarActionPerformed(evt);
            }
        });

        BProx.setText("Próximo");

        jLabel10.setText("R$");

        jLabel11.setText("R$");

        jLabel12.setText("R$");

        jLabel13.setText("R$");

        jLabel14.setText("R$");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("TOTAL R$");

        Pagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(TOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator3)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(q1, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                    .addComponent(q2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(59, 59, 59))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(p4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(p3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7)
                                    .addComponent(q4, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                    .addComponent(q3)
                                    .addComponent(q5)))
                            .addComponent(p5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(v1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(v2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(v3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(v4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(v5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(vv5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                .addComponent(vv4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(vv3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(vv2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(vv1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(193, 193, 193)
                                .addComponent(BAnt)
                                .addGap(18, 18, 18)
                                .addComponent(BProx))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(BRemover)
                                .addGap(52, 52, 52)
                                .addComponent(BAlterar)
                                .addGap(90, 90, 90)
                                .addComponent(BNovo)
                                .addGap(38, 38, 38)
                                .addComponent(BSalvar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CodVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pagamento)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NomeCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel4)
                        .addComponent(CodVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Pagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(v1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vv1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(v2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vv2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(v3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vv3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(v4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vv4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(v5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vv5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TOTAL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BNovo)
                    .addComponent(BSalvar)
                    .addComponent(BAlterar)
                    .addComponent(BRemover))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BAnt)
                    .addComponent(BProx))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void p5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p5ActionPerformed

    private void q1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1ActionPerformed

    private void BSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSalvarActionPerformed
        if(p.contm==9){
             
             JOptionPane.showMessageDialog(null,"Limite maximo de movimentos atingido!!"+"\n"+"Cadastrados:(10)");
         }else{
            int y[] = new int[5], z[] = new int[5];
            int x;
            p.contm++;
            
            p.movimento[p.contm] = new Movimento();
            p.movimento[p.contm].setCodigoVenda(Integer.parseInt(CodVenda.getText()));
            p.movimento[p.contm].setDataVenda(DataVenda.getText());
            p.movimento[p.contm].setTipoPagamento(Pagamento.getText());
            
            
            x = Integer.parseInt(CodigoCliente.getText());
            int t = Buscacod(x);
            
            if(t == 1){
                p.movimento[p.contm].setCodigoC(Integer.parseInt(CodigoCliente.getText()));
                NomeCliente.setText(p.cliente[posicaoc].getNome());
                
            }
            else{
                JOptionPane.showMessageDialog(null,"Cliente não encontrado, insira um codigo de cliente válido.");
                p.contm--;
                return;
                
            }
            
            y[0] = Integer.parseInt(p1.getText());
            z[0] = Buscaprod(y[0]);
            if(z[0] >= 0){
                if(p.produto[z[0]].getQtdEstoque() < Integer.parseInt(q1.getText())){
                    JOptionPane.showMessageDialog(null,"Quantidade 1 maior que o numero de produtos em estoque, insira uma quantidade menor"); 
                    p.contm--;
                    return;
                }
                else{
                    float m1 = p.produto[z[0]].getValorUnitario();
                    float n1 = m1 * Integer.parseInt(q1.getText());
                    p.produto[z[0]].setQtdEstoque(p.produto[z[0]].getQtdEstoque() - Integer.parseInt(q1.getText()));
                    v1.setText(Float.toString(m1));
                    vv1.setText(Float.toString(n1));
                }        
            }
            else{
                    JOptionPane.showMessageDialog(null,"Produto 1 não encontrado, insira um código válido");
                    p.contm--;
                    return;
                    
                        }
            
            y[1] = Integer.parseInt(p2.getText());
            z[1] = Buscaprod(y[1]);
            if(z[1] >= 0){
                if(p.produto[z[1]].getQtdEstoque() < Integer.parseInt(q2.getText())){
                    JOptionPane.showMessageDialog(null,"Quantidade 2 maior que o numero de produtos em estoque, insira uma quantidade menor"); 
                   p.contm--;
                   return;
                }
                else{
                    float m2 = p.produto[z[1]].getValorUnitario();
                    float n2 = m2 * Integer.parseInt(q2.getText());
                    p.produto[z[1]].setQtdEstoque(p.produto[z[1]].getQtdEstoque() - Integer.parseInt(q2.getText()));
                    v2.setText(Float.toString(m2));
                    vv2.setText(Float.toString(n2));
                }        
            }
            else{
                    JOptionPane.showMessageDialog(null,"Produto 2 não encontrado, insira um código válido");
                    p.contm--;
                    return;
                        }
            
            y[2] = Integer.parseInt(p3.getText());
            z[2] = Buscaprod(y[2]);
            if(z[2] >= 0){
                if(p.produto[z[2]].getQtdEstoque() < Integer.parseInt(q3.getText())){
                    JOptionPane.showMessageDialog(null,"Quantidade 3 maior que o numero de produtos em estoque, insira uma quantidade menor");
                    
                }
                else{
                    float m3 = p.produto[z[2]].getValorUnitario();
                    float n3 = m3 * Integer.parseInt(q3.getText());
                    p.produto[z[2]].setQtdEstoque(p.produto[z[2]].getQtdEstoque() - Integer.parseInt(q3.getText()));
                    v3.setText(Float.toString(m3));
                    vv3.setText(Float.toString(n3));   
                }        
            }
            else{
                    JOptionPane.showMessageDialog(null,"Produto 3 não encontrado, insira um código válido");
                    p.cont--;
                    return;
                        }
            
            y[3] = Integer.parseInt(p4.getText());
            z[3] = Buscaprod(y[3]);
            if(z[3] >= 0){
                if(p.produto[z[3]].getQtdEstoque() < Integer.parseInt(q4.getText())){
                    JOptionPane.showMessageDialog(null,"Quantidade 4 maior que o numero de produtos em estoque, insira uma quantidade menor");
                    p.cont--;
                    return;
                }
                else{
                    float m4 = p.produto[z[3]].getValorUnitario();
                    float n4 = m4 * Integer.parseInt(q4.getText());
                    p.produto[z[3]].setQtdEstoque(p.produto[z[3]].getQtdEstoque() - Integer.parseInt(q4.getText()));
                    v4.setText(Float.toString(m4));
                    vv4.setText(Float.toString(n4));   
                }
            }
                else{
                    JOptionPane.showMessageDialog(null,"Produto não 4 encontrado, insira um código válido");
                    p.cont--;
                    return;
                        }
            
            
            y[4] = Integer.parseInt(p5.getText());
            z[4] = Buscaprod(y[4]);
            if(z[4] >= 0){
                if(p.produto[z[4]].getQtdEstoque() < Integer.parseInt(q5.getText())){
                    JOptionPane.showMessageDialog(null,"Quantidade 5 maior que o numero de produtos em estoque, insira uma quantidade menor");
                    p.cont--;
                    return;
                }
                else{
                    float m5 = p.produto[z[4]].getValorUnitario();
                    float n5 = m5 * Integer.parseInt(q5.getText());
                    p.produto[z[4]].setQtdEstoque(p.produto[z[4]].getQtdEstoque() - Integer.parseInt(q5.getText()));
                    v5.setText(Float.toString(m5));
                    vv5.setText(Float.toString(n5));   
                }        
            }
            else{
                    JOptionPane.showMessageDialog(null,"Produto 5 não encontrado, insira um código válido");
                    p.cont--;
                    return;
                        }
            
            p.movimento[p.contm].setTotal(Float.parseFloat(vv1.getText()) + Float.parseFloat(vv2.getText()) + Float.parseFloat(vv2.getText()) + Float.parseFloat(vv4.getText()) + Float.parseFloat(vv5.getText()));
            TOTAL.setText(Float.toString(p.movimento[p.contm].getTotal()));
            
            
            
         
        }
       
        
        BNovo.setEnabled(true);
        BAlterar.setEnabled(true);
        BRemover.setEnabled(true);
        BSalvar.setEnabled(false);
        BAnt.setEnabled(true);
        BProx.setEnabled(true);
        
        NomeCliente.setEnabled(false);
        CodigoCliente.setEnabled(false);
        DataVenda.setEnabled(false);
        NomeCliente.setEnabled(false);
        CodVenda.setEnabled(false);
        Pagamento.setEnabled(false);
        
        p1.setEnabled(false);
        p2.setEnabled(false);
        p3.setEnabled(false);
        p4.setEnabled(false);
        p5.setEnabled(false);
        
        
        q1.setEnabled(false);
        q2.setEnabled(false);
        q3.setEnabled(false);
        q4.setEnabled(false);
        q5.setEnabled(false);
        
        TOTAL.setEnabled(true);
        
        
        MovimentoDAO.salvar(p.movimento[p.contm]);
        
    }//GEN-LAST:event_BSalvarActionPerformed

    private void p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p1ActionPerformed

    private void BNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNovoActionPerformed
        
        BNovo.setEnabled(false);
        BAlterar.setEnabled(true);
        BRemover.setEnabled(true);
        BSalvar.setEnabled(true);
        BAnt.setEnabled(true);
        BProx.setEnabled(true);
        
        NomeCliente.setEnabled(true);
        CodigoCliente.setEnabled(true);
        DataVenda.setEnabled(true);
        NomeCliente.setEnabled(true);
        CodVenda.setEnabled(true);
        Pagamento.setEnabled(true);
        
        p1.setEnabled(true);
        p2.setEnabled(true);
        p3.setEnabled(true);
        p4.setEnabled(true);
        p5.setEnabled(true);
        
        
        q1.setEnabled(true);
        q2.setEnabled(true);
        q3.setEnabled(true);
        q4.setEnabled(true);
        q5.setEnabled(true);
        
        v1.setEnabled(true);
        v2.setEnabled(true);
        v3.setEnabled(true);
        v4.setEnabled(true);
        v5.setEnabled(true);
        
        vv1.setEnabled(true);
        vv2.setEnabled(true);
        vv3.setEnabled(true);
        vv4.setEnabled(true);
        vv5.setEnabled(true);
        
        
        TOTAL.setEnabled(false);
        
        NomeCliente.setText("");
        CodigoCliente.setText("");
        DataVenda.setText("");
        NomeCliente.setText("");
        CodVenda.setText("");
        Pagamento.setText("");
        
        p1.setText("");
        p2.setText("");
        p3.setText("");
        p4.setText("");
        p5.setText("");
        
        
        q1.setText("");
        q2.setText("");
        q3.setText("");
        q4.setText("");
        q5.setText("");
        
        v1.setText("");
        v2.setText("");
        v3.setText("");
        v4.setText("");
        v5.setText("");
        
        vv1.setText("");
        vv2.setText("");
        vv3.setText("");
        vv4.setText("");
        vv5.setText("");
    }//GEN-LAST:event_BNovoActionPerformed

    private void PagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PagamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroMovimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroMovimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroMovimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroMovimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroMovimento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAlterar;
    private javax.swing.JButton BAnt;
    private javax.swing.JButton BNovo;
    private javax.swing.JButton BProx;
    private javax.swing.JButton BRemover;
    private javax.swing.JButton BSalvar;
    private javax.swing.JTextField CodVenda;
    private javax.swing.JTextField CodigoCliente;
    private javax.swing.JTextField DataVenda;
    private javax.swing.JLabel NomeCliente;
    private javax.swing.JTextField Pagamento;
    private javax.swing.JLabel TOTAL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField p1;
    private javax.swing.JTextField p2;
    private javax.swing.JTextField p3;
    private javax.swing.JTextField p4;
    private javax.swing.JTextField p5;
    private javax.swing.JTextField q1;
    private javax.swing.JTextField q2;
    private javax.swing.JTextField q3;
    private javax.swing.JTextField q4;
    private javax.swing.JTextField q5;
    private javax.swing.JLabel v1;
    private javax.swing.JLabel v2;
    private javax.swing.JLabel v3;
    private javax.swing.JLabel v4;
    private javax.swing.JLabel v5;
    private javax.swing.JLabel vv1;
    private javax.swing.JLabel vv2;
    private javax.swing.JLabel vv3;
    private javax.swing.JLabel vv4;
    private javax.swing.JLabel vv5;
    // End of variables declaration//GEN-END:variables
}
